### ISSUE TITLE
Add support for Backblaze application keys

### ISSUE THREAD

**Issue by jimiero** [watchfulli/XCloner-Wordpress#111]
@ovidiul as we discussed it appears currently the used Backblaze library does not work with non-master application keys, as you suggested, can you check if we can extend the library and add support for other application keys?

**Comment by ovidiul** [comment]
Hi @jimiero i have found a fix that can support the application key for Backblaze B2 remote storage, unfortunately this is dependent on the https://github.com/gliterd/backblaze-b2/ package, i have posted a pull request here https://github.com/gliterd/backblaze-b2/pull/49 , hopefully they will add it in their core package, otherwise we will have to clone the package to our repository. So this task is dependent on a third party library code update.

Fix is posted right now in the current milestone package so you can test it, however a composer update might break the changes at any point in the future.
