### ISSUE TITLE
Fatal when trying to access "Generate backups" sections

### ISSUE THREAD

**Issue by jimiero** [watchfulli/XCloner-Wordpress#195]
WordPress: 5.9
xCloner: latest version from branch " 190-composer-fixes"
PHP: 7.4.26

When i try to go to section "Generate backups" section i get a server error:

![Screen Shot 2022-01-27 at 3 38 38 PM](https://user-images.githubusercontent.com/3626762/151370020-fa262e2a-1cf7-425a-84df-84c931e39f04.png)

This is the php error i see in the logs:

PHP Fatal error:  Uncaught Error: Call to undefined method Watchfulli\\XClonerCore\\Xcloner_File_System::directory() in /var/www/html/wp-content/plugins/xcloner/vendor/watchfulli/xcloner-core/src/Xcloner_Api.php:546

**Comment by jimiero** [comment]
![Screen Shot 2022-01-31 at 8 00 38 PM](https://user-images.githubusercontent.com/3626762/151847819-d88422fa-27e2-4c7d-9a8d-09b3b8a58775.png)

**Comment by Shelob9** [comment]
@jimiero Thank you for adding the error. That is the same error as in #546

Can you confirm which commit and branch you are testing with and the exact composer command you ran after setting your repo to that commit and branch?

I ask, as this issue should be fixed by a change to the xcloner-core package and that is installed with Composer.

**Comment by jimiero** [comment]
@Shelob9 from what I can see i'm using this branch https://github.com/watchfulli/XCloner-Wordpress/tree/190-composer-fixes

**Comment by Shelob9** [comment]
Close via #191
