### ISSUE TITLE
Cleanup uploaded archive after restore

### ISSUE THREAD

**Issue by vdrover** [watchfulli/XCloner-Wordpress#88]
Today I did a full-site remote restore. The existing post-restore cleanup worked well to remove the extracted DB and the restore script. However, the backup archive I had uploaded to the target host remained. 

Is there a reasonable way to try an clean this up? Lie comparing the `xcloner-xxxx` folder name to the filename with regex maybe? The restore path could be used to help locate files maybe. 

Thoughts?

**Comment by ovidiul** [comment]
Added an option on the restore page to delete the selected backup archive , this option is only active when restore script is uses as remote end point, otherwise it's disabled, will this work?

<img width="769" alt="Screenshot 2020-06-23 at 12 53 53" src="https://user-images.githubusercontent.com/537751/85389852-a34d8880-b550-11ea-817e-47415c0e89c2.png">

<img width="855" alt="Screenshot 2020-06-23 at 12 52 56" src="https://user-images.githubusercontent.com/537751/85389840-a0529800-b550-11ea-970f-ce4fc1125dea.png">

**Comment by vdrover** [comment]
Looks good.
